require("core.plugin_config.lualine")
-- require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.rust_config")
require("core.plugin_config.lsp_config")
require("core.plugin_config.auto_complete")
-- require("core.plugin_config.tokyo_scheme")
require("core.plugin_config.nvim_cmp_and_snippet")
require("core.plugin_config.neogit")
